services:
  s3:
    image: docker.io/chrislusf/seaweedfs:latest
    ports:
    - "9333:9333"
    - "8888:8888"
    - "8333:8333"
    - "8111:8111"
    environment:
    - AWS_ACCESS_KEY_ID=admin
    - AWS_SECRET_ACCESS_KEY=key
    command:
    - "server"
    - "-s3"
  grafana:
    image: grafana/otel-lgtm
    ports:
    - "3000:3000"
    - "4317:4317"
    - "4318:4318"
