name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      minio:
        image: bitnami/minio:latest
        ports:
        - "9000:9000"
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: password
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "1.18"
    - uses: actions/checkout@v2
    - name: Download Modules
      run: go mod download
    - name: Build
      run: go build -ldflags="-X cas/version.GitCommit=${{ github.ref}} -X cas/version.Prerelease="""
    - name: Test
      env:
        CAS_S3_TEST_ENDPOINT: "http://localhost:9000"
      run: go test -v ./...
    - name: Publish Release
      if: github.ref == 'main'
      run: echo "github release"
